### ISSUE TITLE
Unable to use with `ndarray` version 0.14

### ISSUE THREAD

**Issue by appetrosyan** [paulkernfeld/ndarray-csv#12]
Hi. I'm trying to use the library and it causes an issue with mismatched types. 

```
error[E0308]: mismatched types
  --> src/main.rs:19:33
   |
19 |         writer.serialize_array2(&array)?;
   |                                 ^^^^^^ expected struct `ndarray::ArrayBase`, found struct `ArrayBase`
   |
   = note: expected reference `&ndarray::ArrayBase<ndarray::data_repr::OwnedRepr<_>, ndarray::dimension::dim::Dim<[usize; 2]>>`
              found reference `&ArrayBase<OwnedRepr<{integer}>, Dim<[usize; 2]>>`
   = note: perhaps two different versions of crate `ndarray` are being used?

error[E0308]: try expression alternatives have incompatible types
  --> src/main.rs:25:35
   |
25 |     let array_read: Array2<u64> = reader.deserialize_array2((2, 3))?;
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `ArrayBase`, found struct `ndarray::ArrayBase`
   |
   = note: expected struct `ArrayBase<OwnedRepr<u64>, Dim<[usize; 2]>>`
              found struct `ndarray::ArrayBase<ndarray::data_repr::OwnedRepr<_>, ndarray::dimension::dim::Dim<[usize; 2]>>`
   = note: perhaps two different versions of crate `ndarray` are being used?

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `analgesic`

To learn more, run the command again with --verbose.
```

Here's my `Cargo.toml`

```
[package]
name = "analgesic"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.14"
ndarray-csv = "0.4.0"
csv = "1"
```

**Comment by paulkernfeld** [comment]
Try ndarray-csv 0.5! I think the problem is that ndarray-csv 0.4 only works with ndarray 0.13. The [cargo tree](https://crates.io/crates/cargo-tree) tool can be useful for debugging this type of issue.

**Comment by appetrosyan** [comment]
That worked!

I would point out, that the `Cargo.toml` on this mirror is for version 0.4.0, which I think also needs to be bumped? I assumed 0.4.0 was the latest version.

**Comment by paulkernfeld** [comment]
Oops, thanks for pointing that out! I forgot to push to master! 😁
